disabled_rules:
  - todo

opt_in_rules:
  - empty_count
  - force_unwrapping
  - explicit_init

included:
  - NOCTO
  - Sources

excluded:
  - .build
  - NOCTO.xcodeproj

line_length:
  warning: 140
  error: 180

identifier_name:
  min_length:
    warning: 2

force_cast: error
force_try: error

reporter: "xcode"
